version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Helsinki
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Helsinki
    versioning-strategy: increase-if-necessary
    groups:
      python-runtime:
        dependency-type: production
      python-development:
        dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Helsinki
    groups:
      go-runtime:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: "/src/huntx/connectors/v2ray_collector"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Helsinki
    groups:
      collector-go-runtime:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5

