// Flat ESLint configuration for the HUNTX dashboard.
//
// The dashboard renders attacker-controlled text: proxy names, SNI values, and
// hostnames all arrive from public channels. The rules below are weighted
// towards catching the mistakes that turn that text into executable markup,
// and towards catching dead code that hides an unfinished feature.

import js from "@eslint/js";
import globals from "globals";

export default [
  {
    // Generated by the pipeline and by Go's wasm toolchain. Never linted.
    ignores: [
      "docs/assets/js/data.js",
      "docs/assets/js/wasm_exec.js",
      "docs/assets/css/tailwind.css",
      "docs/artifacts/**",
      "outputs/**",
      "outputs_dev/**",
      "node_modules/**",
    ],
  },

  js.configs.recommended,

  {
    files: ["docs/assets/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        // decoder.js is imported by the Node test suite as well as the page,
        // and guards its Node-only paths with `typeof Buffer !== "undefined"`.
        Buffer: "readonly",
      },
    },
    rules: {
      // Correctness.
      eqeqeq: ["error", "smart"],
      "no-var": "error",
      "prefer-const": "error",
      "no-implicit-globals": "error",
      "no-throw-literal": "error",
      "no-return-assign": "error",
      "no-unmodified-loop-condition": "error",
      "no-constant-binary-expression": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",

      // Dead code. An assigned-but-unused local is usually a feature that was
      // started and abandoned, which is exactly how `clashYaml` survived.
      "no-unused-vars": [
        "error",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
      "no-unreachable": "error",
      "no-useless-return": "error",

      // Injection surface. `eval` and friends have no legitimate use here.
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
    },
  },

  {
    // Service worker and the wasm worker run off the main thread, with a
    // different global object and script-scoped `importScripts`.
    files: ["docs/sw.js", "docs/assets/js/wasm-worker.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.serviceworker,
        ...globals.worker,
        // Exported by wasm_exec.js and by the Go wasm module once it starts.
        Go: "readonly",
        huntx_decode_subscription: "readonly",
      },
    },
    rules: {
      // These files are classic scripts, not modules. Top-level declarations
      // are their normal scope and are not leaking into a shared global.
      "no-implicit-globals": "off",
    },
  },

  {
    files: ["tests/**/*.mjs", "*.mjs", "*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];
